Zadania 1-3
coders-school/multithreading pull request #10
Opened 2020-02-22 20:33 UTC by WBigaj

Szafirmag zadania 1-3

2020-02-22 22:38 UTC, ziobron reviewed
+ za ciekawe pomiary 👍 
Drobne rzeczy można poprawić.

2020-02-22 22:38 UTC, ziobron commented on Szafirmag/Zadanie 2/SizeTest.cc
> +	const size_t hardwareThread = std::thread::hardware_concurrency();
co jeśli `hardware_concurrency()` zwróci 0?

2020-02-22 22:38 UTC, ziobron commented on Szafirmag/Zadanie 2/SizeTest.cc
> +	auto start = std::chrono::steady_clock::now();
do dokładniejszych pomiarów czasu polecam używać `high_resolution_clock` zamiast `steady_clock`

2020-02-22 22:38 UTC, ziobron commented on Szafirmag/Zadanie 2/readme.txt
> +modyfikacjami stylistycznymi.
oprócz moich 2 uwag raczej nic nie trzeba ulepszać :)

2020-02-22 22:38 UTC, ziobron commented on Szafirmag/Zadanie 3/Zadanie3.cc
> +	const size_t hardwareThread = thread::hardware_concurrency();
tutaj też pytanie, co się stanie gdy `hardware_concurrency()` zwróci nam 0? :)

2020-02-22 22:38 UTC, ziobron commented on Szafirmag/Zadanie 3/Zadanie3.cc
> +			}, begin, end,value, ref(results[i]));
formatowanie się rozjechało. Spacje z tabami się wymieszały

2020-02-22 22:38 UTC, ziobron commented on Szafirmag/Zadanie 3/Zadanie3.cc
> +int pararelCountIF(IT first, IT last, V value) {
parametr `V value` lepiej nazwać `P predicate`. Dzięki szablonom zadziała to na dowolnym typie, a sama nazwa predykat jest ogólniejsza, więc jest bardziej intuicyjne że można tam lambdę przekazać.

2020-02-24 11:44 UTC, ziobron commented
Zad 1 - 38 pkt
Zad 2 - 10 pkt
Zad 3 - 18 pkt
Punktualność 15 pkt

Jeśli chcesz dostać max za 2 i 3 to popraw jeszcze ten problem gdy `hardware_concurrency()` zwraca 0.

2020-04-13 19:06 UTC, WBigaj commented
Dodanie zadania 5 i 7

2020-04-15 12:21 UTC, ziobron requested changes
Zad 5 +5 pkt
Zad 7 +10 pkt
Czekam na poprawki, wtedy przyznam więcej punktów :)

2020-04-15 12:21 UTC, ziobron commented on Szafirmag/Zadanie5/Zadanie5b.cxx
> +    f.y = local_y;
W takim przypadku zadziała, ale gdybyśmy chcieli mimo wszystko na bieżąco aktualizować wartość f.y po każdym obrocie pętli, to należałoby użyć alignas(64). Zazwyczaj linia cache'u ma długość 64 bajtów. Dzięki temu zaobserwujesz przyspieszenie programu bez modyfikacji funkcji. Jedynie do typu int w strukturze musisz dopisać ten modyfikator. Spróbujesz i podeślesz wyniki?

2020-04-15 12:21 UTC, ziobron commented on Szafirmag/Zadanie7/Zadanie7.1.cxx
> +        if(libmail::send_mail(placeHolder, placeHolder) == 1){
```suggestion
        if(libmail::send_mail(placeHolder, placeHolder)){
```
Poza tym, chyba nie chcemy tam 2 placeholderów tylko adres email i wiadomość do wysłania

2020-04-15 12:21 UTC, ziobron commented on Szafirmag/Zadanie7/Zadanie7.1.cxx
> +        futures.push_back(std::move(future));
```suggestion
        futures.emplace_back(promise.get_future());
```

2020-04-15 12:21 UTC, ziobron commented on Szafirmag/Zadanie7/Zadanie7.2-3.cxx
> +            promise.set_value(e.what());
```suggestion
            promise.set_exception(std::current_exception());
```

2020-04-15 12:21 UTC, ziobron commented on Szafirmag/Zadanie7/Zadanie7.2-3.cxx
> +    }
Ta pętla powinna być zintegrowana z powyższą i tutaj trzeba przy pobieraniu wartości z future objąć ją w blok try/catch. W catch powinniśmy wypisać, że wysyłanie się nie powiodło oraz wyświetlić powód z wyjątku - e.what()

2020-04-15 14:03 UTC, WBigaj commented
Zajmę się tym po wyzwaniu wydajnego kodu na kurs online z C++,które będę robił w weekend. Chciałbym prosić o aktualizacje punktów za zrobione testy(tydzień temu zrobiłem wszystkie osiem). Pozdrawiam i życzę miłego dnia Wiktor Bigaj! 
            
          
     
      
       
        Dnia 15 kwietnia 2020 14:22 Łukasz Ziobroń &lt;notifications@github.com&gt; napisał(a):
       
    
       
         
 @ziobron  requested changes on this pull request. 

 Zad 5 +5 pkt  
Zad 7 +10 pkt  
Czekam na poprawki, wtedy przyznam więcej punktów :) 

 In  github.com Szafirmag/Zadanie5/Zadanie5b.c : 
 &gt; +    int local_y = f.y;
+    for (int i = 0; i &lt; 1000000; ++i)
+        ++local_y;
+    f.y = local_y;
 
 W takim przypadku zadziała, ale gdybyśmy chcieli mimo wszystko na bieżąco aktualizować wartość f.y po każdym obrocie pętli, to należałoby użyć alignas(64). Zazwyczaj linia cache&#39;u ma długość 64 bajtów. Dzięki temu zaobserwujesz przyspieszenie programu bez modyfikacji funkcji. Jedynie do typu int w strukturze musisz dopisać ten modyfikator. Spróbujesz i podeślesz wyniki? 

 

 In  github.com Szafirmag/Zadanie7/Zadanie7.1. : 
 &gt; +int main()
+{
+    std::vector&lt;std::future&lt;std::s futures;
+    std::vector&lt;std::thread&gt; threads;
+    libmail::randomize_results();
    std::vector&lt;std::string&gt; responsible_devs = {
+        &#34;dev1@company.com&#34;,
+        &#34;dev2@company.com&#34;,
+        &#34;dev3@company.com&#34;,
+        &#34;dev4@company.com&#34;,
+        &#34;dev5@company.com&#34;,
+    };
+    auto function = [] (std::promise&lt;std::string&gt; promise)
+    {
+        const std::string placeHolder = &#34;&#34;;
+        if(libmail::send_mail(placeHol placeHolder) == 1){
 
⬇️ Suggested change
 -        if(libmail::send_mail(placeHol placeHolder) == 1){
+        if(libmail::send_mail(placeHol placeHolder)){
 

 Poza tym, chyba nie chcemy tam 2 placeholderów tylko adres email i wiadomość do wysłania 

 

 In  github.com Szafirmag/Zadanie7/Zadanie7.1. : 
 &gt; +        std::future&lt;std::string&gt; future = promise.get_future();
+        futures.push_back(std::move(fu 
⬇️ Suggested change
 -        std::future&lt;std::string&gt; future = promise.get_future();
-        futures.push_back(std::move(fu        futures.emplace_back(promise.g 


 

 In  github.com Szafirmag/Zadanie7/Zadanie7.2- : 
 &gt; +    libmail::randomize_results();
    std::vector&lt;std::string&gt; responsible_devs = {
+        &#34;dev1@company.com&#34;,
+        &#34;dev2@company.com&#34;,
+        &#34;dev3@company.com&#34;,
+        &#34;dev4@company.com&#34;,
+        &#34;dev5@company.com&#34;,
+    };
+    auto function = [] (std::promise&lt;std::string&gt; promise)
+    {
+        const std::string placeHolder = &#34;&#34;;
+        try{
+            libmail::send_mail(placeHolder placeHolder);
+            promise.set_value(&#34;OK&#34;);
+        } catch(const std::runtime_error&amp; e){
+            promise.set_value(e.what());
 
⬇️ Suggested change
 -            promise.set_value(e.what());
+            promise.set_exception(std::cur 


 

 In  github.com Szafirmag/Zadanie7/Zadanie7.2- : 
 &gt; +    for(int i=0; i &lt; responsible_devs.size(); i++) {
+        std::cout &lt;&lt; &#34;Sending mail to: &#34; &lt;&lt; responsible_devs.at(i) &lt;&lt; &#34; - &#34; &lt;&lt; futures.at(i).get()  &lt;&lt; std::endl;
+    }
 
 Ta pętla powinna być zintegrowana z powyższą i tutaj trzeba przy pobieraniu wartości z future objąć ją w blok try/catch. W catch powinniśmy wypisać, że wysyłanie się nie powiodło oraz wyświetlić powód z wyjątku - e.what() 

 —  You are receiving this because you modified the open/close state.  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .

2020-04-15 14:26 UTC, ziobron commented
> Chciałbym prosić o aktualizacje punktów za zrobione testy(tydzień temu zrobiłem wszystkie osiem). 
Zaktualizowane :)

2021-01-07 09:52 UTC, closed without merging