Zadanie3 done
coders-school/multithreading pull request #3
Opened 2020-02-20 07:09 UTC by ChopSeeGuy

2020-02-20 11:39 UTC, ziobron approved these changes
Plusy za przekazywanie przez const& 👍 
Wszystko ładnie podzielone na funkcje.

2020-02-20 11:39 UTC, ziobron commented on zadanie3.cpp
> +                const decltype(startStandard) &stopStandard,
Ładnie używasz decltype :)

2020-02-20 11:40 UTC, ziobron commented
A jak wyglądają czasy przy takim przyspieszeniu? Ile masz rdzeni? :)

2020-02-20 12:59 UTC, ziobron requested changes
Drobne rzeczy do poprawki :)

2020-02-20 12:59 UTC, ziobron commented on zadanie3.cpp
> +    const size_t maxThreads = std::thread::hardware_concurrency();
Co jeśli `hardware_concurrency` zwróci 0?

2020-02-20 12:59 UTC, ziobron commented on zadanie3.cpp
> +    auto stop3 = std::chrono::steady_clock::now();
Lepiej używać `high_resolution_clock` zamiast `steady_clock` do pomiarów czasu działania algorytmów.

2020-02-20 14:50 UTC, ChopSeeGuy commented
> A jak wyglądają czasy przy takim przyspieszeniu? Ile masz rdzeni? :)

Pararel algorithm for [400000000]: 1111220us

Normal algorithm for [400000000]: 4810939us

Pararel algorithm for [100000000]: 280342us

Normal algorithm for [100000000]: 1208112us

Pararel algorithm for [5000]: 74us

Normal algorithm for [5000]: 124us

Pararel algorithm for [2500]: 74us

Normal algorithm for [2500]: 59us

Posiadam 8 rdzeni.

2020-02-21 17:30 UTC, ziobron approved these changes
Ok, wygląda dobrze :)

2020-02-24 11:24 UTC, ziobron commented
84 punkty za całość, czyli max. Zamykam :)

2020-02-24 11:24 UTC, closed without merging