zadanie 3 + zadanie 2 (z dodanym std::execution::par)
coders-school/multithreading pull request #9
Opened 2020-02-22 19:58 UTC by MonikaZelechowska

2020-02-22 22:01 UTC, ziobron requested changes
Podobają mi się testy 👍 
Można drobne poprawki wprowadzić.
Napiszcie tutaj w dyskusji jeszcze jakie są czasy działania.

2020-02-22 22:01 UTC, ziobron commented on PraceDomowe/zad2_accumulate.cpp
> +	const size_t hardwareThread = std::thread::hardware_concurrency();
co jeśli `hardware_concurrency()` zwróci 0?

2020-02-22 22:01 UTC, ziobron commented on PraceDomowe/zad2_accumulate.cpp
> +    auto start5 = std::chrono::steady_clock::now();
Formatowanie się rozjeżdża. Czasem są taby a czasem spacje :) Musicie się wyrównać w tej kwestii.

2020-02-22 22:01 UTC, ziobron commented on PraceDomowe/zad3_count_if.cpp
> +    const size_t dataSize = std::distance(first, last);
Dwukrotnie wołacie funkcję `std::distance`. Można tylko raz :) Koszt w przypadku wektora jest co prawda mały, ale gdyby była tutaj używana lista to już miałoby to złożoność liniową.

2020-02-22 22:01 UTC, ziobron commented on PraceDomowe/zad3_count_if.cpp
> +	const size_t hardwareThread = std::thread::hardware_concurrency();
podobnie jak w zadaniu 2, co jeśli tutaj dostaniemy 0?

2020-02-22 22:01 UTC, ziobron commented on PraceDomowe/zad3_count_if.cpp
> +        counter += element;
można `std::accumulate` tutaj wykorzystać, ale wasza wersja też jest poprawna. 
W pętli element będzie kopiowany. Aby uniknąć zbędnej kopii można tam dać referencję.

2020-02-24 11:40 UTC, ziobron commented
Zad 2 - 10 pkt.
Zad 3 - 16 pkt.
Jak chcecie zdobyć max to napiszcie jeszcze jakie czasy działania u was wyszły i poprawcie ten problem że `hardware_concurrency()` może zwrócić 0.
Jak nie to dajcie znać, to zamknę tego PR.

PS. Polecam kolejne zadania lub projekt robić na innych branchach, wtedy jak zgłosicie mi z nimi PR to poprzednich zadań nie wrzucicie.

2020-02-24 14:54 UTC, kdoroszko commented
Łukasz poniżej czasy z uruchomienia programu:

--- Algorithm running time calculation ---
Parallel algorithm for 1'000'000 element vector lasted: 78285us
STL algorithm for 1'000'000 element vector lasted: 96930us
STL algorithm with execution policy for 1'000'000 element vector lasted: 79109us

2020-02-25 15:26 UTC, ziobron commented
OK, max punktów :) Zamykam.

2020-02-25 15:26 UTC, closed without merging